title: Katherine Hébert
theme: hugo-story
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
Params:
  description: 
  favicon: yes
  logo: images/profile.jpeg
  social:
    email: katherine.hebert@mcgill.ca
    github: https://github.com/katherinehebert/
    twitter: https://bsky.app/profile/katherinehebert.bsky.social
  marketing:
    analytics:
      google_analytics: 'G-4G022THGHT'
